### ISSUE TITLE
Errors when running 'install' and 'gitignore' commands

### ISSUE THREAD

**Issue by felladrin** [appetizermonster/unity-packman#2] opened 2017-03-04 18:44 UTC
Hey there! Thanks for creating this awesome tool!
I'd like to share two bugs I've run into:

1. When running `unity-packman install appetizermonster/Unity3D-QuickSearch` (after `unity-packman init`):

```
> unity-packman install appetizermonster/Unity3D-QuickSearch
- unity-packman 0.0.17
installing dependencies...

cloning https://github.com/appetizermonster/Unity3D-QuickSearch.git
copying to stage: appetizermonster.Unity3D-QuickSearch
complete
updating packman.json...
Error: Uri has wrong format: undefined
    at Object.toPkgInfo (C:\Users\User\AppData\Roaming\npm\node_modules\unity-packman\src\uri-parser.js:7:11)
    at Object.makeDependenciesUnique (C:\Users\User\AppData\Roaming\npm\node_modules\unity-packman\src\packman-json.js:40:31)
    at install (C:\Users\User\AppData\Roaming\npm\node_modules\unity-packman\src\commands\install.js:119:33)
    at next (native)
    at onFulfilled (C:\Users\User\AppData\Roaming\npm\node_modules\unity-packman\node_modules\co\index.js:65:19)
```

The content of generated `packman.json` is:

```
{
  "name": "TccGameClient"
}
```

----

2. When running `unity-packman gitignore`:

```
> unity-packman gitignore
- unity-packman 0.0.17
C:\Users\User\AppData\Roaming\npm\node_modules\unity-packman\cli.js:23
    packman.gitIgnore().catch(console.error);
            ^

TypeError: packman.gitIgnore is not a function
    at Command.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\unity-packman\cli.js:23:13)
    at Command.listener (C:\Users\User\AppData\Roaming\npm\node_modules\unity-packman\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (C:\Users\User\AppData\Roaming\npm\node_modules\unity-packman\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\User\AppData\Roaming\npm\node_modules\unity-packman\node_modules\commander\index.js:458:21)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\unity-packman\cli.js:47:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

Anyway, I've added `.packman` manually to .gitignore.

**Comment by hsandt** [comment] 2017-04-22 21:34
I also had the 1st error `Error: Uri has wrong format: undefined`
I simply added to the packman.json:
`"dependencies": []`

This solved the error and after install, the dependencies were filled with the newly installed package. I guess the script is not able to initialize the dependencies list by itself.

I am checking `install.js:118`
`  let newDependencies = [].concat(packmanObj.dependencies).concat(targetDependencies);
`
but I don't see anything abnormal, if packmanObj.dependencies are null on json parsing, they are replaced with [] a few lines before anyway.

By the way, at the end of the operation a .packman folder remains, containing a complete copy of the package repository, which may become heavy if you install many. At first I thought it was because of the mentioned error and somewhat the cleaning step was interrupted, but apparently it wasn't. I assume the folder remains for testing purpose? If I delete it, it will be installed again next time I update the package anyway.

**Comment by nihakue** [comment] 2018-10-20 21:23
The gitignore problem is caused by type in cli.js which is referring to `packman.gitIgnore` when the actual command name is `packman.gitignore`.

**Closed as completed** 2020-03-08 18:43 UTC
